name: Deploy Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Push Build Files to Public Repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          npm install --global serve
          serve -l 80
          
